apiVersion: apps/v1
kind: Deployment
metadata:
  name: tele-dep
  labels:
    app: tele-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tele-dep
  template:
    metadata:
      labels:
        app: tele-dep
    spec:
      containers:
      - name: tele-dep-con
        image: 313826143473.dkr.ecr.us-west-2.amazonaws.com/telematichub-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-cred
